### ISSUE TITLE
Disable automatic KVO notications for ...Value setters

### ISSUE THREAD

**Issue by smic** [rentzsch/mogenerator#107]
If you observe the ...Value properties you will get two notifications if you set the value. One by the the automatic notification and one by the keyPathsForValuesAffectingValueForX method.

I know that observing the ...Value properties doesn't make sense. Performance-wise it will be much better to observe the original property. But it might impact the performance if the automatic notification is enabled.

+ (NSSet *)keyPathsForValuesAffectingValueForKey:(NSString *)key {
	NSSet *keyPaths = [super keyPathsForValuesAffectingValueForKey:key];
	
	if ([key isEqualToString:@"blaValue"]) {
		NSSet *affectingKey = [NSSet setWithObject:@"bla"];
		keyPaths = [keyPaths setByAddingObjectsFromSet:affectingKey];
	}

	return keyPaths;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(NSString *)key {
    if ([key isEqualToString:@"blaValue"]) {
		return NO;
	}
    
    return [super automaticallyNotifiesObserversForKey:key];
}

**Comment by justin** [comment]
Closing this out since it's 3 years old. If this is still an issue for you can you re-open.
