### ISSUE TITLE
Sort descriptors for fetch requests in data model

### ISSUE THREAD

**Issue by scottroberts140** [rentzsch/mogenerator#119]
I'd like to see an auto-generated method for fetch requests in the data model that allows sort descriptors to be specified. For example, in addition to:

+ (NSArray *)fetchSomething:(NSManagedObjectContext*)moc_ PARAMETER:(Entity*)PARAMETER_

and its version with the NSError parameter, another version with the signature

+ (NSArray *)fetchSomething:(NSManagedObjectContext*)moc_ PARAMETER:(Entity*)PARAMETER_ sortDescriptors:(NSArray *)sortDescriptors_

**Comment by justin** [comment]
This is kind of beyond the scope of what we do. I'd recommend adding a category or extension to add whatever methods you want to your class.
