### ISSUE TITLE
Test fails if there is a space in the derived data path

### ISSUE THREAD

**Issue by danielctull** [rentzsch/mogenerator#151]
I have my derived data set to point to a path with a space in it on my iMac, so it fails there. I have tested this on my MacBook Air, where the tests pass when the path is `~/Desktop/DerivedData`, but fail when the path is `~/Desktop/Derived Data`. I've tried looking into the Rakefile, but I'm not overly familiar with ruby.

**Comment by Isuru-Nanayakkara** [comment]
I've facing a similar issue and it's driving me up the wall. My project name has a space in between. How do you handle it in the path. This is what I have now.
```
/usr/local/bin/mogenerator -m Mogen\ Magic/Mogen\ Magic/Magic.xcdatamodeld -O --template-var arc=true --machine-dir Mogen\ Magic/Model/Machine --human-dir Mogen\ Magic/Model/Human --swift
```
I have no problem with projects with single word names.
