### ISSUE TITLE
ARC and object attributes

### ISSUE THREAD

**Issue by hiaw** [rentzsch/mogenerator#155]
Hi,

I had a bug that I scratch my head for hours to figure out what's wrong. Here's the code.

    NSPredicate *predicate = [NSPredicate predicateWithFormat:@"%@ == %@", ChildAttributes.child_code, defaultChildCode];

Once I change it to

    NSPredicate *predicate = [NSPredicate predicateWithFormat:@"child_code == %@", defaultChildCode];

it work again. I suspect there's something to do with the object attributes ```__unsafe_unretained```. I'm using ARC.

Thanks.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
