### ISSUE TITLE
Warnings for method collision

### ISSUE THREAD

**Issue by zorn** [rentzsch/mogenerator#16]
One thing that seems to burn me often is giving one of my Entities an attribute with a name that clashes with the other methods in Cocoa. 

It would be cool if mogenerator gave me a warning that although I have an attribute named description the class mogenerator will create will have a method that will collide with NSObject's -description.

I've seen similar issues with -name -type -value and a few others.

**Comment by jhemingw** [comment]
The bizarre thing I'm experiencing on my iOS project, is that of the 15 or so entities I have, primitiveType and setPrimitiveType are only generated for one of the classes! This on version 1.28.

**Comment by eytanbiala** [comment]
@rentzsch  Is there a way to suppress the primitive accessors, and possibly also some of the other generated code as well?
