### ISSUE TITLE
Import problem with sub entity

### ISSUE THREAD

**Issue by talesp** [rentzsch/mogenerator#167]
I have an entity FeedItem with a sub entity Style. In Core Data modeler I have the class set equals the name of the entity, in order to generate de machine/human files for both parent (FeedItem) and child (Style) entities.

But on the machine file for Style, I have

```Objective-C
@interface _Style : FeedItem {}
```
As `FeedItem.h` is not imported anywhere for Style.h (of _Style.h), I get the following error:

`Cannot find interface declaration for 'FeedItem', superclass of '_Style'`

How should I fix this? The only thing that I can think is include manually on _Style.h, but as I have mogenerator as a pre-build phase, I would loose it.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
