### ISSUE TITLE
1.27 asserts on -[MOGeneratorApp setModel:] (current rev is OK)

### ISSUE THREAD

**Issue by fritza** [rentzsch/mogenerator#169]
The latest public release (1.27) asserts in `-[MOGeneratorApp setModel:]` for a stupid-simple `xcdatamodeld`. This is fixed in the latest revision, (`e8a05a316`), but I have to explain mogenerator to a readership that can't be trusted to clone a Git repo.

Supplying the `.xcdatamodel` inside the `.xcdatamodeld` cures the problem in 1.27.

The notes for 1.27 advertise the handling of  `.xcdatamodeld` as an enhancement in that release.

Can a 1.28 possibly be packaged-up in the next few weeks?

> Always recognizing I may be doing something boneheaded.

Sample project in [Dropbox](https://www.dropbox.com/s/1xcccdmkjxje0ta/KillMeMogenerator.zip).

``` bash
$ mogenerator -v
mogenerator 1.27. By Jonathan 'Wolf' Rentzsch + friends.

$ pwd
/Users/fritza/Desktop/KillMeMogenerator/KillMeMogenerator

$ ls
Base.lproj			KillMeMogenerator-Info.plist
Images.xcassets			KillMeMogenerator-Prefix.pch
KMGAppDelegate.h		Model.xcdatamodeld
KMGAppDelegate.m		en.lproj
KMGViewController.h		main.m
KMGViewController.m

$ mogenerator --model Model.xcdatamodeld/
Assertion failed: (model), function -[MOGeneratorApp setModel:], file /Users/wolf/code/github/mogenerator/mogenerator.m, line 681.
Abort trap: 6

$ mogenerator --model Model.xcdatamodeld/Model.xcdatamodel/
4 machine files and 4 human files generated.

$ 
```

**Comment by LanziVision** [comment]
You are able to circumvent this fatal error if you don't user Xcode's generated Core data model.
Just leave that box empty. Then in your project go to 'New'->'file'->'core data'->'data model'

Verified that this works with Xcode v-6.4
![demo](https://cloud.githubusercontent.com/assets/11592843/9866000/faf880b0-5b11-11e5-94ca-a125923c7ca3.png)

**Comment by justin** [comment]
If this is still an issue in Xcode 7, please open a new issue and we can see if theres something we can do.
