### ISSUE TITLE
Use instancetype as insertInManagedObjectContext: return type when possible

### ISSUE THREAD

**Issue by corristo** [rentzsch/mogenerator#171]
This can be solved by editing template and replacing `id` with `instancetype`, but it would limit compatibility with older compilers (as far as I get it's important for this project, so...). Dance like this should work though:

    #if __has_feature(instancetype)
    instancetype
    #else
    id
    #endif insertInManagedObjectContext...

But it's too verbose. Ideas?

**Comment by justin** [comment]
`instancetype` should be the default as of now. Closing this out.
