### ISSUE TITLE
MoGen does not give an error message when -- options are incorrectly coded

### ISSUE THREAD

**Issue by LostInTheTrees** [rentzsch/mogenerator#172]
Edit: See my last comment for the resolution of my original problem. One of my dashes was a long dash not a regular dash. MoGen did not give an error message, which took me a full day to find.

This is probably my own problem, but I haven't been able to figure out another way to contact you. My build phase command line is this currently:

mogenerator  –-template-var arc=true -m PT1/Data/DataModel.xcdatamodeld -O PT1/Data

Files are generated, but it seems to be ignoring the ARC flag. I have tried variations on this line, but I always get this in my machine files:

extern const struct BillingAccountAttributes {
    NSString *accountActive;
    ...
}  BillingAccountAttributes;

This gives an ARC error. I do not know what it is supposed to generate for ARC, except I found one mention on StackOverflow of __unsafe_unretained in front of the entries in the struct.

I have looked for some indication or output from Mogen in the XCode build log and don't anything that shows what option it thinks are accepted. I also tried redirecting stdout from MoGen and didn't see anything there. What might I be doing wrong?

It may be relevant that I am on XCode 5 and iOS7, but I don't see how exactly.

Thanks for your work on this.

-Bob

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
