### ISSUE TITLE
__unsafe_unretained Leaks

### ISSUE THREAD

**Issue by jodm** [rentzsch/mogenerator#176]
I have never used this before mogenerator before but have taken over a project using it.

I have found this question and stackoverflow: Why is MoGenerator falling afoul of ARC?

I have taken a look at the project in Instruments and monitoring leaks and there are 14,000+ leaked NSObjectID (_NSObjectID_64_2) objects.

I am associating these leaks with the __unsafe_unretained properties - What can I do about these? I can't dealloc them in the machine generated class as they will simply be overwritten when I next generate them?

Please advise.

James

**Comment by justin** [comment]
If this is still an issue with Xcode 7 and mogenerator 1.29 please open a new issue.
