### ISSUE TITLE
CI / error: Could not create bundle folder for versioned model at <path>

### ISSUE THREAD

**Issue by zielinskik** [rentzsch/mogenerator#189]
Hi,
Most attempts to build the project bu Hudson ends in failure, only when Questionnaire.xcdatamodeld is called with the appropriate prarameter and in specific order build succeeds. This order is
Questionnaire.xcdatamodeld normal armv7
Questionnaire.xcdatamodeld normal armv7s
Questionnaire.xcdatamodeld normal arm64

otherwise
console log looks like that:

Running mogend
mogenerator --model "/hudson/workspace/iOS_TTQuiz_master_incremental/SeeingAssistant-Survey/Sources/Models/Questionnaire.xcdatamodeld/Questionnaire.xcdatamodel" --output-dir "/hudson/workspace/iOS_TTQuiz_master_incremental/SeeingAssistant-Survey/Sources/Models/"
0 machine files and 0 human files generated.
/Applications/Xcode.app/Contents/Developer/usr/bin/momc -XD_MOMC_TARGET_VERSION=10.6 "/hudson/workspace/iOS_TTQuiz_master_incremental/SeeingAssistant-Survey/Sources/Models/Questionnaire.xcdatamodeld" "/hudson/workspace/iOS_TTQuiz_master_incremental/build/Release-iphoneos/TT Quiz.app/Questionnaire.momd"
/hudson/workspace/iOS_TTQuiz_master_incremental/SeeingAssistant-Survey/Sources/Models/Questionnaire.xcdatamodeld:0: error: Could not create bundle folder for versioned model at '/hudson/workspace/iOS_TTQuiz_master_incremental/build/Release-iphoneos/TT Quiz.app/Questionnaire.momd'

RuleScriptExecution SeeingAssistant-Survey/Sources/Models/Questionnaire.xcdatamodeld normal armv7s
    cd /hudson/workspace/iOS_TTQuiz_master_incremental
    setenv ACTION build
    setenv AD_HOC_CODE_SIGNING_ALLOWED NO
(...)
setenv YACC yacc
    setenv arch armv7s
    setenv variant normal
    /bin/sh -c echo\ \"Running\ mogend\"\
\"${SRCROOT}/SeeingAssistant-Survey/Scripts/mogend.sh\"
Running mogend
mogenerator --model "/hudson/workspace/iOS_TTQuiz_master_incremental/SeeingAssistant-Survey/Sources/Models/Questionnaire.xcdatamodeld/Questionnaire.xcdatamodel" --output-dir "/hudson/workspace/iOS_TTQuiz_master_incremental/SeeingAssistant-Survey/Sources/Models/"
0 machine files and 0 human files generated.
/Applications/Xcode.app/Contents/Developer/usr/bin/momc -XD_MOMC_TARGET_VERSION=10.6 "/hudson/workspace/iOS_TTQuiz_master_incremental/SeeingAssistant-Survey/Sources/Models/Questionnaire.xcdatamodeld" "/hudson/workspace/iOS_TTQuiz_master_incremental/build/Release-iphoneos/TT Quiz.app/Questionnaire.momd"

** BUILD FAILED **

The following build commands failed:
	RuleScriptExecution SeeingAssistant-Survey/Sources/Models/Questionnaire.xcdatamodeld normal arm64
(1 failure)
ERROR # 65 : Compilation failed
DONE with script: CompleteBuild.sh (65)
Showing first 200 notices only

** BUILD FAILED **

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
