### ISSUE TITLE
Entities with string attributes have their properties generated with "strong" instead of "copy".

### ISSUE THREAD

**Issue by DesiGuy421** [rentzsch/mogenerator#190]
Referencing this Twitter thread: https://twitter.com/aqgunja/status/432994099688263680

**Comment by mgrebenets** [comment]
Bump. Would be nice at least to have a command line switch. Our guidelines is to use `copy` for `NSString` properties, so it would be great to have generated code to conform as well.

**Comment by seanm** [comment]
This is a dupe of #41.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
