### ISSUE TITLE
Skipping entity generation purposefully

### ISSUE THREAD

**Issue by trevorsheridan** [rentzsch/mogenerator#193]
In my .xcdatamodel I've setup `Entity A` thats parent entity is `Parent Entity`. `Parent Entity`'s class is simply set to MMRecord and it's set as an abstract entity. Right now mogenerator will generate files for `Parent Entity` called MMRecord. MMRecord is part of a framework so I don't want to generate a file for this entity. Is it possible to tell mogenerator that I would like it to skip it?

**Comment by justin** [comment]
Not presently. I'm not really sure of a good way to tackle that honestly.
