### ISSUE TITLE
Can't handle fetch request templates with SUBQUERY?

### ISSUE THREAD

**Issue by itsthejb** [rentzsch/mogenerator#198]
Hi,

First of all, such excellent work on this tool. Don't know how I could cope without it.

I've just added the following fetch request template to my model:

`(userIdentifier == $userIdentifer) AND (SUBQUERY($course.levels, $level, $level.thingIdentifiers CONTAINS $thingIdentifier).@count > 0)`

This fails to compile with mogenerator with the following exception:

`Assertion failed: ([[(NSComparisonPredicate*)predicate_ leftExpression] expressionType] == NSKeyPathExpressionType), function -[NSEntityDescription(customBaseClass) _processPredicate:bindings:], file /tmp/mogenerator-KSyw/mogenerator-1.27/mogenerator.m, line 207.
zsh: abort      /usr/local/bin/mogenerator -m <redacted>`

I had a quick look at the source code, and it seems that mogenerator doesn't handle `NSSubqueryExpressionType` at all. At least I can't find any reference to it in code and this would explain the assertion/exception.

I should note that the predicate works in code and due to the nature of the exception, I don't *think* there's an error with the expression. Please correct me if I'm wrong, however.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
