### ISSUE TITLE
Swift enhancements

### ISSUE THREAD

**Issue by mrichtsfeld** [rentzsch/mogenerator#212]
Hi, 

First of all, great project!

Since Swift will be the new state of the art for coding cocoa(touch) I'm diving into it, writing my new project already with Swift. I use mogenerator since I use CoreData and was always happy with it. 

Now I try using it with Swift and stumbled over some issues. Of course I know that this is still pre-release, but I want to help making it better so I have a few questions. Depending on the outcome I will also implement the changes and contribute them to the project. 

So here are my issues: 

I don't get the namespace prefix used when creating swift classes e.g. 

```
class MyPrefix.MyClass: NSManagedObject {    
}
```  

This gives me an error so it does not seem to work currently. 

Furthermore I'm not sure why the Attributes for all classes are enums because then it is always necessary to add a `toRaw()`to get the actual value. Wouldn't it be better to use a struct instead like: 

```
struct MyClassAttributes {  
    static let myAttribute: String = "myAttribute"  
}
``` 

Please tell me what you think so I can implement whatever is necessary.

**Comment by justin** [comment]
We are tracking Swift 2.0 changes in #302. If you have any feedback, please give that a look.
