### ISSUE TITLE
[Enhancement] Split the generated fetch request method

### ISSUE THREAD

**Issue by pbtura** [rentzsch/mogenerator#213]
Currently, the code generation for CoreData fetch requests generates a single method for each fetch that handles building and executing the query. This makes it very difficult to override the fetch request behavior in the subclass. My suggestion is to split the generated method for each fetch into two methods, one that build and returns the NSFetchRequest and the other that takes an existing request and executes it.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
