### ISSUE TITLE
Can't use property name enums in Swift.

### ISSUE THREAD

**Issue by Scenario** [rentzsch/mogenerator#218]
When using the Swift template in 1.28, the Swift compiler in Xcode Beta 3 will not allow the use of your auto-generated string constants for property names. It issues the error "'MyEntityAttributes' is not convertible to 'String'" on any line of code like this one:

if anInstanceOfMyEntity.valueForKey(MyEntityAttributes.aProperty).integerValue != whatever

Is this an Apple bug or a mogenerator bug?

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
