### ISSUE TITLE
We desperately need *Value methods in the Swift template.

### ISSUE THREAD

**Issue by Scenario** [rentzsch/mogenerator#219]
The Swift compiler in Xcode Beta 3 still doesn't play well with the Cocoa classes produced by  mogenerator. It requires us to use KVC exclusively to get or set any property in an NSManagedObject entity, and that is a major burden on us lowly devs.

In Objective-C, the .h/.m files generated by mogenerator produce type-safe convenience getters and setters of the form "myPropertyValue". But those are all missing from the Swift template in 1.28.

Please consider adding these unless there's a good reason not to. :)

**Comment by justin** [comment]
We are working on adjusting how we generate Swift in #302. If you have feedback, let's put it there.
