### ISSUE TITLE
Swift _Class to-many accessors recurse infinitely

### ISSUE THREAD

**Issue by fritza** [rentzsch/mogenerator#227]
Consider entity `Passer`, which is one-to-many with entity `Games`. `mogenerator` creates these extensions in `_Passer.swift`:

```swift
extension _Passer {

    func addGames(objects: NSSet) {
        self.gamesSet().unionSet(objects)
    }

    func removeGames(objects: NSSet) {
        self.gamesSet().minusSet(objects)
    }

    func addGamesObject(value: Game!) {
        self.gamesSet().addObject(value)
    }

    func removeGamesObject(value: Game!) {
        self.gamesSet().removeObject(value)
    }
}
```

When I get to the line

```swift
            newGame.passer = passer
```

… Core data hits the inverse, the `@NSManaged` `games` set.

This results (surprisingly rapidly — Swift is beginning to live up to its potential for speed) in a stack 112,165 frames deep, recurring through `addGamesObject(Game!)`.

I infer that `NSManagedObject` implements the to-many Set proxies in terms of the already-synthesized (just never declared) `add{Relationship}Object` (etc.) methods. That’s what I see in the disassembly.

I commented the to-many extension out, and the application runs as expected. I imagine this is a Simple Matter Of Programming™ with the Swift template, and I’d offer a pull request, but there are so many damn branches, I don’t know which I should work against. 

Anyone else seeing this?

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
