### ISSUE TITLE
Crash in getter for inverse in To Many-to-To Many relationships

### ISSUE THREAD

**Issue by Scenario** [rentzsch/mogenerator#228]
When using the pre-release 1.28 Swift template, I'm getting crashes in mogenerated getters.

The offending relationships are To Many-to-To Many, defined like so:

    Category.items (ordered, nullify) <<—>> Item.categories (unordered, nullify)

The mogenerated code for one of the inverses looks like this:

    @NSManaged
    var categories: NSSet

    func categoriesSet() -> NSMutableSet! {
        self.willAccessValueForKey("categories")                  <<< EXC_BAD_ACCESS code=2

        let result = self.mutableSetValueForKey("categories")

        self.didAccessValueForKey("categories")
        return result
    }

Is this a known issue and are these cases being tested for 1.28 release? Thanks!

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
