### ISSUE TITLE
UserInfo keys : Wiki doc updated + renaming suggestion

### ISSUE THREAD

**Issue by AliSoftware** [rentzsch/mogenerator#232]
Hi there,

Just to let you know that I [updated your "Core Data user Info Keys" wiki page](https://github.com/rentzsch/mogenerator/wiki/Core-Data-User-Info-Keys) to add some missing keys, especially the ones recently added by the recent merge requests.

> _I left some cells blank (`…`) because I am not sure about the aim of those keys (but at least we have an exhaustive list now), so feel free to complete the missing descriptions._

I also created [a wiki article about using enums for attribute types](https://github.com/rentzsch/mogenerator/wiki/Using-enums-as-types). Don't hesitate to review and modify it if needed.

---

Also, for clarity and consistency reasons, I suggest that we rename every UserInfo key to be **prefixed by `"mogenerator."`**, like what you did for `mogenerator.customBaseClass` and `mogenerator.readonly`.

* This ensures consistency and avoid potential conflicts with other tools that are usng those UserInfo keys as well (like MagicalImport or Groot)
* We may also find better names for some, like `attributeValueClassName` and `attributeValueScalarType` could maybe be merged into one `mogenerator.customType`?
* We may still accept the old names for retro-compatibility (e.g. `result = [[self userInfo] objectForKey:@"mogenerator.customType"] ?: [[self userInfo] objectForKey:@"attributeValueClassName"];`)

---

Also related to #162 & #207

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
