### ISSUE TITLE
Manual KVO notifications necessary with -mutableSetValueForKey:?

### ISSUE THREAD

**Issue by bryanesmith** [rentzsch/mogenerator#240]
First, thank you very much for developing and maintaining this project.

In the motemplate files, when generating `-fooSet` helper method, why wrap the call to `-mutableSetValueForKey:` with KVO notifications (`-willAccessValueForKey`, `-didAccessValueForKey`)? 

This method isn't primitive, so shouldn't it automatically handle KVO notifications?

**Comment by justin** [comment]
We are changing this in the Swift templates in #302. I imagine this could be fixed in Objective-C too.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
