### ISSUE TITLE
no accessor generated for an undefined transient attribute (aka "transient id typed attribute")

### ISSUE THREAD

**Issue by altimac** [rentzsch/mogenerator#252]
Hi!

Using mogenerator 1.28,

I've noticed that a transient attribute with type set to "undefined" (aka id typed) (I want to store an NSDictionary in this property) does not get its accessors exported to the machine file. It is listed in the attributes struct though as 	__unsafe_unretained NSString *trs_context;
A "boolean typed transient attribute" is correctly exported and get its accessors generated as expected.

I suspect it's a bug as I don't understand why shouldn't it be exported.
As a workaround I'm going to use good old KVC to set it.

**Comment by hirad** [comment]
I have the same problem. The machine files are missing the Core Data generated accessors for transient properties.

**Comment by pronebird** [comment]
Same issue. Which accessors are generated for transient properties?

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
