### ISSUE TITLE
Support access control in swift

### ISSUE THREAD

**Issue by tkrajacic** [rentzsch/mogenerator#259]
I am using a framework to contain the model for multiple applications. Since those applications need to use the managed object subclasses, these need to be __public__. This seems currently not possible with mogenerator (aside from manually editing the machine generated files), since without any access control qualifier, all classes are __internal__.

Would it be possible to support having managed object classes public? (Or am I going at it the wrong way?)

**Comment by ahknight** [comment]
Copy and edit the Swift template to meet your needs. :)

**Comment by bonebox** [comment]
Running into this same issue.

**Comment by ktomek** [comment]
+1

**Comment by regexident** [comment]
How about using the "User Info" key-value feature of each model entity (from right within the Core Data editor) for specifying the access control (with `internal` being the implicit default)?

User Info:

    Key:        Value:
    mo_access = "public"

The benefit compared to having a default (and enforced) setting or yet another command-line option would be the ability to define access control on a finely granular per-entity basis.

**Comment by justin** [comment]
Everything should show up as public as of now. If you are wanting more fine grain control, let's open a separate issue and discuss.
