### ISSUE TITLE
Template tweak to simplify primitive accessor naming scheme?

### ISSUE THREAD

**Issue by Air-Craft** [rentzsch/mogenerator#260]
Would it be possible, given the template language, to make it such that if you use a common prefix for database fields, for example "mSort" and "mPrice", that mogenerator can make the primitive accessors be simply "sort" and "price" rather than "sortValue" and "priceValue"?  Having had a brief look, it seems that it might require some sort of search/replace function...

**Comment by justin** [comment]
If you want to tweak things like this, adjusting the templates yourself and passing them through the `--template-path` var is the recommended approach.
