### ISSUE TITLE
Generating fetch from Xcode Model (Swift)

### ISSUE THREAD

**Issue by JoaoSobral** [rentzsch/mogenerator#262]
Hi,

I noticed that the mogenerator is generating incorrectly the fetch code giving a compile build error. It is related with optionals. The fetches were created on the Xcode model.

**From the fetch func this is what the mogenerator, generates, giving compile error**:
let fetchRequest = **model**.fetchRequestFromTemplateWithName("FetchName", substitutionVariables: substitutionVariables
...
let results = managedObjectContext.executeFetchRequest(**fetchRequest**, error: &error)

**However it should be generating (notice the unwrapping of model and fetchRequest)**
let fetchRequest = **model?**.fetchRequestFromTemplateWithName("FetchName", substitutionVariables: substitutionVariables
...
let results = managedObjectContext.executeFetchRequest(**fetchRequest!**, error: &error)

--
Thanks for your support and dev on this generator!
Best regards,
Joao Goncalves

**Comment by TheMory** [comment]
Hi, 

Same problem here. Is this issue has been corrected in a dev version ?

Thx a lot for providing this great tool.

Regards.

**Comment by modecolems** [comment]
Hi guys, no news about this issues ?

Cause mogenerator is just unusable while we have to manually alter generated files containing fetch request method on each build...

Thx for your help.

Regards.

**Comment by JoaoSobral** [comment]
Agree on that :-(

On Mon, Apr 13, 2015 at 5:54 PM, modecolems <notifications@github.com>
wrote:

> Hi guys, no news about this issues ?
>
> Cause mogenerator is just unusable while we have to manually alter
> generated files containing fetch request method on each build...
>
> Thx for your help.
>
> Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rentzsch/mogenerator/issues/262#issuecomment-92409628>
> .
>



-- 
Cumprimentos,
João Gonçalves

**Comment by justin** [comment]
This is going to be fixed soon. We are tracking the changes in #302.
