### ISSUE TITLE
Optional issue for NSNumber

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [rentzsch/mogenerator#264]
Generated classes don't reflect the optional changes for attributes of the type `NSNumber`. If I tick off the optional checkbox for an attribute with the type `NSNumber` and run mogenerator, in the generated class, it still shows the `?` for that attribute.

**Comment by rpstro02** [comment]
This issue still exists

**Comment by schartyom** [comment]
still exists. It's connected to https://github.com/rentzsch/mogenerator/issues/286

**Comment by justin** [comment]
We'd accept a patch for this.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
