### ISSUE TITLE
Boolean values are shown as NSNumber

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [rentzsch/mogenerator#265]
This happens in generated Swift classes. Attributes with the type `Boolean` are generated as `NSNumber` in the generated Machine classes.

**Comment by oeed** [comment]
+1 Although I suspect that this might be this for a reason. That said, there could be away to make them show as booleans. It is quite annoying having to convert them or do == 0 etc.

**Comment by justin** [comment]
We are working to change this in #302.

**Comment by akabab** [comment]
any update on swift template?
