### ISSUE TITLE
Swift modules and class names

### ISSUE THREAD

**Issue by sbooth** [rentzsch/mogenerator#269]
I'm relatively new to Swift so I apologize in advance if I'm missing something obvious.

All of the Apple documentation I could find on using Core Data with Swift (for example [Implementing Core Data Managed Object Subclasses](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/WritingSwiftClassesWithObjective-CBehavior.html) and [WWDC 2014 What's New in Core Data](https://developer.apple.com/videos/wwdc/2014/?include=225#225)) says that in order to use a Swift subclass of `NSManagedObject` the class name in the `Class` field of the model entity inspector must be prefixed with the Swift module name.  The example they give is `MyCoreDataApp.Person`.

![screen shot 2015-02-18 at 9 33 23 am](https://cloud.githubusercontent.com/assets/9965/6248877/3f1372d8-b751-11e4-9242-9e79030e100c.png)

I created my model this way and using both Xcode 6.1 and 6.3b the generated subclass is in a file called `MyCoreDataApp.swift` and look like:

    class MyCoreDataApp: NSManagedObject {
        @NSManaged var name: String
    }

I think this is clearly a bug in Xcode but I'm providing the information for reference.  I normally use mogenerator to generate `NSManagedObject` subclasses.  For the same test app when I run `mogenerator --swift --model MyCoreDataApp.xcdatamodeld` I get two output files: `_MyCoreDataApp.Person.swift` and `MyCoreDataApp.Person.swift`.  Neither of them will compile.

The contents of `_MyCoreDataApp.Person.swift` are:

```
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// Make changes to MyCoreDataApp.Person.swift instead.

import CoreData

enum MyCoreDataApp.PersonAttributes: String {
    case name = "name"
}

@objc
class _MyCoreDataApp.Person: NSManagedObject {

    // MARK: - Class methods

    class func entityName () -> String {
        return "Person"
    }

    class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.entityName(), inManagedObjectContext: managedObjectContext);
    }

    // MARK: - Life cycle methods

    override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext!) {
        super.init(entity: entity, insertIntoManagedObjectContext: context)
    }

    convenience init(managedObjectContext: NSManagedObjectContext!) {
        let entity = _MyCoreDataApp.Person.entity(managedObjectContext)
        self.init(entity: entity, insertIntoManagedObjectContext: managedObjectContext)
    }

    // MARK: - Properties

    @NSManaged
    var name: String?

    // func validateName(value: AutoreleasingUnsafePointer<AnyObject>, error: NSErrorPointer) {}

    // MARK: - Relationships

}
```

and the contents of `MyCoreDataApp.Person.swift` are:

```
@objc(MyCoreDataApp.Person)
class MyCoreDataApp.Person: _MyCoreDataApp.Person {

	// Custom logic goes here.

}
```

The compiler output would be too long to post in its entirety but here is a representative sample:

```
/tmp/MyCoreDataApp/MyCoreDataApp/_MyCoreDataApp.Person.swift:6:19: Expected '{' in enum

/tmp/MyCoreDataApp/MyCoreDataApp/_MyCoreDataApp.Person.swift:6:45: Statement cannot begin with a closure expression

/tmp/MyCoreDataApp/MyCoreDataApp/_MyCoreDataApp.Person.swift:7:5: Enum 'case' is not allowed outside of an enum
```

All of the problems are traceable to including the Swift module name in the `Class` name.  I've yet to create a working Core Data app in Swift so I don't know if it is truly required.  Is this a bug in the toolchain or mogenerator?

**Comment by fizker** [comment]
You are missing something obvious. `class MyCoreDataApp.Person` is not legal, as `.` cannot be part of a class name.

I don't know why they said that you need to prefix with something, but it works fine for me without any type of prefix. So name your custom class `Person` and you are good to go.

----

It could be argued that mogenerator should replace the `.` with something else (like `_`) or fail with an explicit warning, but I have no strong opinion on that.

**Comment by sbooth** [comment]
I understand the class name isn't legal but it is what mogenerator creates.  Leaving the Swift module name out in the model editor for the entity's class doesn't work;  in my testing Swift `NSManagedObject` subclasses without the module name give the following error:

```
CoreData: warning: Unable to load class named 'Person' for entity 'Person'.  Class not found, using default NSManagedObject instead.
```

When I change the entity's class name to `MyCoreDataApp.Person` it works correctly.  I think if mogenerator stripped out the module name things would work correctly.

**Comment by dave256** [comment]
@sbooth You're not doing something correct, but I'm not certain exactly what. I've got some sample code here:

 https://github.com/dave256/DDRCoreDataKit

That uses an updated version of mogenerator (also in my github account) that makes classes/methods public and allows you to use the existing command line argument (that is used in Objective-C to specify an include file) to specify the Swift import statement to import DDRCoreDataKit.

All the code is written using Swift-1.2 (there's a Swift-1.2 branch) so you need Xcode 6.3 beta 2 right now. You can take a look at what the Core Data model file looks like for the classes and how I import it.

There's a version here that uses DDRCoreDataKit as a framework (using git submodules)

https://github.com/dave256/CoreDataSample

**Comment by sbooth** [comment]
@dave256 Thanks for sharing the sample.  I created a pared-down application that exhibits the problem at https://github.com/sbooth/SwiftCoreDataTest .  Using Xcode 6.3b2 the project, as committed, fails at runtime.  Adding the module name (CoreDataTestApp) fixes the problem.

**Comment by sbooth** [comment]
I figured out why your code works and mine doesn't- you explicitly specify the name of the symbol  for your `NSManagedObject` subclass (using `@objc(Event)`).  That syntax makes Swift classes available in Objective-C without any namespacing and thus Core Data can find them.  Without the explicit symbol name Core Data fails at runtime because it can't find the custom subclass since it's located in the module's namespace.

So to bring this back to mogenerator, in my opinion to work properly for those accustomed to Swift mogenerator should handle namespacing properly and not require explicit symbol naming.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
