### ISSUE TITLE
Fetch request comes out with wrong parameter type

### ISSUE THREAD

**Issue by sjmills** [rentzsch/mogenerator#270]
I recently change my object model so one entity has an attribute of type Transformable. When I run mogenerator on it, the resulting file has a wrong type for a parameter in a fetch request that access this transformable attribute.

The entity looks like:
Folder:
Attributes:
url, Transformable, uses a custom NSValueTransformer to convert between NSData and NSURL.

The fetch request stored in the model looks like:
Fetch all Folder objects where:
Expression: url.path LIKE[c] $THE_URL

The generated .h file should look like this:
+ (NSArray*)fetchFoldersForURL:(NSManagedObjectContext*)moc_ THE_URL:(NSObject*)THE_URL_ ;
+ (NSArray*)fetchFoldersForURL:(NSManagedObjectContext*)moc_ THE_URL:(NSObject*)THE_URL_ error:(NSError**)error_;

But it looks like this:
+ (NSArray*)fetchFoldersForURL:(NSManagedObjectContext*)moc_ THE_URL:(i*)THE_URL_ ;
+ (NSArray*)fetchFoldersForURL:(NSManagedObjectContext*)moc_ THE_URL:(i*)THE_URL_ error:(NSError**)error_;

The generated .m file has a similar error.

Looks like something is just parsing the data type wrong when it includes a period maybe? I think my fetch request is technically correct, since the url attribute is an NSURL after it's been transformed, and NSURL has a property named "path". It does work.

For now, I'll switch to simply comparing the urls with "url == $THE_URL", but that loses the ability to do case-insensitive compares.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
