### ISSUE TITLE
Suggestion on class methods for Swift Gen.

### ISSUE THREAD

**Issue by Prince2k3** [rentzsch/mogenerator#271]
Hello,

First I want to mention that I really like mogenerator. It has saved me a lot of time over the years and help me to focus on the work aspect of the code to get things done. 

Ok ... my suggestion. 

I notice when generating the Managed Objects. I get these class methods in every class file. I was thinking there should be an extension to NSManagedObject so that its written once. 
``` 
class func entityName () -> String 
class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! 
``` 

What do you guys think? Yes? No?

**Comment by atomicbird** [comment]
In the current approach, `entityName` returns a hard-coded value in the machine value that's different for every generated machine file, and `entity` relies on `entityName` to get that string. It's probably possible to move `entity` to an extension/protocol but it doesn't seem worthwhile for a single method. It's probably also possible to move `init(entity:insertIntoManagedObjectContext:)` to an extension, but it's still not a lot of code for an extra file, compared with the number of other methods. On the whole I'm not sure that adding the extension actually makes things simpler.
