### ISSUE TITLE
Defining a Parent-Class without an Entity

### ISSUE THREAD

**Issue by georgbachmann** [rentzsch/mogenerator#273]
Hello,

in my project I subclassed almost every Entity from one common Parent-Entity which had things like a remoteID, updatedAt, createdAt and so on... Today I learned that this sucks because now everything get's thrown into one giant table inside SQLite which will make my app slow one day...

So now before really shipping my app I'd like to refactor that... So now I would need to generate a subclass of NSManagedObject that is not an entity in the Core-Date Editor but only in Code...

Is there a way to now tell mogenerator that classes it generates should inherit from that one? Maybe use the UserInfo Key-Value thingy for that?

Any ideas on that one?

Cheers,
Georg

**Comment by bgulanowski** [comment]
There's an option on the executable to set the parent class. `--base-class CLASS`

**Comment by georgbachmann** [comment]
is there a way to only set that on certain entities but not on all?

**Comment by bgulanowski** [comment]
I don't know. You could just do it for all of them, and allow those that don't use features of that class to opt out of them. It would make your design more consistent if all entities descended from the same base class.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
