### ISSUE TITLE
Framework & Protocol Support for Swift and Objective-C

### ISSUE THREAD

**Issue by webair** [rentzsch/mogenerator#274]
Hello

I am using a a third pary module (Swift) which requires protocols to the managed objects. AFAIK with the current release either is not yet supported by mogenerator. My suggestion would be to add new parameter:

--base-protocols

In Objective-C: className : baseClass<Protocol> 
In Swift: className : baseClass[,]Protocol (, if base class is defined)

Additonal a framework support would also be nice, for example with the parameter

--base-framework

In Objective-C: #import <framework/framework.h>
In Swift: import framework

What do you think about this? 

If time is an issue, I would be happy to create a pull request if necessary adding those features.

**Comment by dave256** [comment]
I've done some of this in my fork. There already is a flag for doing the import statement in Objective-C

--base-class-import 

so I just reused it.

https://github.com/dave256/mogenerator/commits/swift-public

Specifically:

https://github.com/dave256/mogenerator/commit/44875a88f17c6080cff7ec19cdd70ae0d13f3cbf

**Comment by webair** [comment]
Hi Dave

Thanks for the hint. So importing frameworks actually would not be a big issue. 

For implementing protocols i see more or less two options:

1. Adding a new parameter for protocls (so Objective-C could also easily implement it)
2. Adding protocols through the ---base-class-import statment (would only work for swift). The problem here would be that the swift template adds the override statement to the function, if a base class is provided.

From my view, i would prefer the first solution. I will try it out in a fork and look if it gets accepted or not ;)

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
