### ISSUE TITLE
entityName: conflicts with others lib

### ISSUE THREAD

**Issue by chrux** [rentzsch/mogenerator#277]
Hi, As suggestion, we should try to enable a parameter which allow us to set prefix to entityName method, if true or 1 we rename the method to be mo_entityName for example. This is in order to make it safe to use with other libs such us https://github.com/Alecrim/AlecrimCoreData or https://github.com/tadija/AERecord

**Comment by justin** [comment]
This is out of scope for mogenerator i believe.
