### ISSUE TITLE
Mogenerator release update plans

### ISSUE THREAD

**Issue by andreyslyusar** [rentzsch/mogenerator#278]
Hi,

Are there any plan for next public release of mogenerator with extended swift support. It would be very nice to get https://github.com/rentzsch/mogenerator/pull/245, https://github.com/rentzsch/mogenerator/issues/266, https://github.com/rentzsch/mogenerator/pull/258 and etc.

**Comment by jimijon** [comment]
Yes, I am looking forward to this too.

**Comment by anilreddi** [comment]
Is swift 1.2 version in development? Right now all the files generated by moGenerator needs manual fixing before ready to use

**Comment by ronnieliew** [comment]
Likewise, looking forward to seeing the Swift-centric PR merged.

**Comment by rentzsch** [comment]
I'm too busy to look at this myself, but I have a couple of friends vetting those PRs. Probably won't be much longer now.

**Comment by justin** [comment]
Yeah. I'm planning to dedicate some time vetting weekend to it. I want it too.

**Comment by atomicbird** [comment]
The `feature/swift12` branch is gradually moving forward on this.

**Comment by andreyslyusar** [comment]
Sounds great. Thanks a lot for your commitment.

**Comment by mikkelee** [comment]
👍

**Comment by mplorentz** [comment]
Now that Swift 2 has been announced it would be really great to get an official release for 1.2 before it gets passed by.

**Comment by justin** [comment]
See #302 for swift 2 tracking.
