### ISSUE TITLE
Commented out validateXXX funcs for swift are invalid

### ISSUE THREAD

**Issue by Aloisius** [rentzsch/mogenerator#281]
The commented out validate functions in the swift machine template look something like this:

     // func validate<$Attribute.name.initialCapitalString$>(value: AutoreleasingUnsafePointer<AnyObject>, error: NSErrorPointer) {}

However, the format should be:

     // func validate<$Attribute.name.initialCapitalString$>(value: AutoreleasingUnsafeMutablePointer<AnyObject?>, error: NSErrorPointer) -> Bool {}

It was changed on 8/4/2014 https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/RevisionHistory.html:

>Updated the Pointers section to reflect that UnsafePointer has been replaced with UnsafeMutablePointer, ConstUnsafePointer has been replaced with UnsafePointer, and AutoreleasingUnsafePointer has been replaced with AutoreleasingUnsafeMutablePointer. 

The return of Bool however seems to be undocumented, but the resulting function is supposed to return a Bool and funcs with that signature appear to be called properly.

**Comment by atomicbird** [comment]
Fixed on branch feature/swift12. Thanks!
