### ISSUE TITLE
How to roll-back to an older version?

### ISSUE THREAD

**Issue by rcharlton** [rentzsch/mogenerator#282]
I need to rollback to release 1.27 but the package installer prevents this. 
Is there a way to cleanly uninstall?

**Comment by rentzsch** [comment]
probably delete the installation receipt (but I forgot where OS X stores those nowadays) and reinstall

**Comment by rcharlton** [comment]
Thanks for the hint. The following does the trick:
sudo rm /var/db/receipts/com.rentzsch.mogenerator.*

**Comment by rentzsch** [comment]
Great. Yeah that jogs my memory.
