### ISSUE TITLE
propertyDescription.optional not set because XML attribute is not present

### ISSUE THREAD

**Issue by mattbauch** [rentzsch/mogenerator#286]
I was wondering why, after incorporating the changes of #245, my Swift machine files didn't use optionality correctly. So I did a couple of tests and I think I found a bug. 

Currently mogenerator uses something like this to create `NSPropertyDescription` (and others) from the XML CoreData model:

    // NSPropertyDescription+momcom.m:33

    } else if ([attributeName isEqualToString:@"optional"]) {
        [propertyDescription setOptional:[attributeString isEqualToString:@"YES"]];
    }

Unfortunately the Xcode model editor does not create an `optional` xml attribute if the core data attribute is not optional. So `propertyDescription.optional` is never set. So it is still set to its default value. Which in this case is `YES`, which is the exact opposite from what it should be.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
