### ISSUE TITLE
Duplicate import entries in --includeh file

### ISSUE THREAD

**Issue by Sega-Zero** [rentzsch/mogenerator#289]
Having a model:
![model](https://cloud.githubusercontent.com/assets/2203199/8324898/62e33828-1a5d-11e5-8227-1757aadf6d24.jpg)
The `Comment` entity inherits from `Post` entity and does not contain any properties, just a relationship to `Post` entity. When specifying `--includeh` key, the result file contains duplicate entries:
```objective-c
#import "Photo.h"
#import "Post.h"
#import "Post.h"
#import "User.h"
```
I believe this is not good =)

**Comment by justin** [comment]
We'd accept a patch for this, but it's probably not a high priority fix for me to tackle personally.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
