### ISSUE TITLE
uninstalling mogenerator 1.28

### ISSUE THREAD

**Issue by pablobfs** [rentzsch/mogenerator#291]
I need to downgrade to version 1.27 and i´m unable to remove mogenerator from my computer
already removed /usr/bin/mogenerator and other references ive found, but my mac still stops me when i try to install version 1.27 since i already have 1.28.

Thank you very much and kudos for the tool

**Comment by Gabpacheco** [comment]
Hi, @pablobfs! After almost reset my mac, I found a solution for this issue...
run this commands and be happy!

`sudo rm -rif /private/var/db/receipts/com.rentzsch.mogenerator.plist`
`sudo rm -rif /private/var/db/receipts/com.rentzsch.mogenerator.bom`
`sudo rm -rif /usr/bin/mogenerator`

**Comment by addisonwebb** [comment]
here's a script to uninstall https://gist.github.com/addisonwebb/231e24604f809948e589

**Comment by addisonwebb** [comment]
Sure thing. I have an updated one for 1.29 as well.
https://gist.github.com/addisonwebb/cdebf1ff6399529eb201

**Comment by duongdvag** [comment]
> Hi, @pablobfs! After almost reset my mac, I found a solution for this issue...
> run this commands and be happy!
> 
> `sudo rm -rif /private/var/db/receipts/com.rentzsch.mogenerator.plist`
> `sudo rm -rif /private/var/db/receipts/com.rentzsch.mogenerator.bom`
> `sudo rm -rif /usr/bin/mogenerator`

The path changed to `/usr/local/bin/mogenerator` on macOS 10.14
