### ISSUE TITLE
Swift 1.2 NSSet removed 

### ISSUE THREAD

**Issue by hardikdevios** [rentzsch/mogenerator#294]
i have One-to-Many Relationship From parent to child So when i tried to generate Models .. its taking NSSet instead of Set with extension in Parent class so i have to Remove/Change that manually so i am hoping before Swift 2.0 official release it may get fixed but i am currently searching for Temporary work-around .. So Any chance of better option Guys ?

**Comment by mattbauch** [comment]
mogenerator has a [Swift 1.2 branch](https://github.com/rentzsch/mogenerator/tree/feature/swift12)

**Comment by hardikdevios** [comment]
@mattbauch Hey mate thanks for this i know about this branch but how should i use this in Xcode project because i am using with Run script mode where 1.28 is installed using brew is there any steps i can use this branch by adding it in my project , thanks mate for help

**Comment by hardikdevios** [comment]
#284 Solved my issue thanks closing now i can now merge my changes any way thanks buddy
