### ISSUE TITLE
Swift 1.2 public relationship issue 

### ISSUE THREAD

**Issue by hardikdevios** [rentzsch/mogenerator#295]
![screen shot 2015-07-19 at 6 54 13 pm](https://cloud.githubusercontent.com/assets/6657591/8766072/ca7acd2c-2e47-11e5-91c5-c082b459bb0c.png)

Patient_routine has **many** Groups
Groups can have **one** Patient_routine

So i think making the relationship public of patient causes issue.

so  i have commented ```@NSManaged public``` Also in the **machine.swift.motemplate** with this 
After ```<$else$>``` condition and generated new Bin and overwrite my machine files and It works.

```   
 // MARK: - Relationships
<$foreach Relationship noninheritedRelationships do$>
<$if Relationship.isToMany$>
    @NSManaged public
    var <$Relationship.name$>: <$Relationship.immutableCollectionClassName$>

<$else$>
//    @NSManaged public
    var <$Relationship.name$>: <$Relationship.destinationEntity.managedObjectClassName$><$if Relationship.isOptional$>?<$endif$>

    // func validate<$Relationship.name.initialCapitalString$>(value: AutoreleasingUnsafeMutablePointer<AnyObject>, error: NSErrorPointer) -> Bool {}
<$endif$>
<$endforeach do$>
```

So do we have any more specific cases in Relationships? or this solution will work now for Temporary base.. If somebody have this issue happened in near future if they have better solution than,Please share .

# Update

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
