### ISSUE TITLE
Swift 2.0 Human readable files requires Foundation

### ISSUE THREAD

**Issue by kostiakoval** [rentzsch/mogenerator#299]
@objc attribute used without importing module 'Foundation'
```
@objc(Entity) // Error here
public class Entity: _Entity {
	// Custom logic goes here.
}
```

**Fix** - Add  `Import Foundation`

**Comment by rentzsch** [comment]
Hey Kostiantyn,
Thanks for the Pul Request. It looks like mogenerator 1.30 will be a Swift 2.0 release, which will be in the mainline instead of relegated to `contributed templates`. Please co-ordinate with @justin on #302.
