### ISSUE TITLE
add Swift 2.0 support

### ISSUE THREAD

**Issue by kostiakoval** [rentzsch/mogenerator#300]
make a new branch for Swift 2.0 so people can contribute to it

**Comment by kostiakoval** [comment]
I've added templates for Swift 2.0 
https://github.com/rentzsch/mogenerator/issues/299
How can I make it available in mogenerator

**Comment by elsurudo** [comment]
:+1: this would be handy

**Comment by 3lvis** [comment]
Nice one! I wish this project wasn't abandoned. It had a lot of potential.

**Comment by justin** [comment]
See #302 for tracking this.
