### ISSUE TITLE
Add support for lightweight generics in relationships

### ISSUE THREAD

**Issue by pronebird** [rentzsch/mogenerator#306]
For example this:

```objc
@interface _Notification : NSManagedObject {}
@property (nonatomic, strong) NSSet *relatedApps;
@end 
```

to this:

```objc
@interface _Notification : NSManagedObject {}
@property (nonatomic, strong) NSSet<App *> *relatedApps;
@end 
```

**Comment by rentzsch** [comment]
Sure. I think this probably can be generated today with only a template-level change.

**Comment by pronebird** [comment]
I've added generics here: 

https://github.com/pronebird/mogenerator/commit/1084c798ced91b01b2f559c65ed775f296e459b6

But I have no idea how to test/deploy mogenerator. Would you give me a helping hand here in testing or at least.

Also I think we need a new option for that maybe `--generics` to enable this feature.

**Comment by idomizrachi** [comment]
I had the same issue but with the Swift template, so I forked and did the following change in the template:
https://github.com/idomizrachi/mogenerator/commit/d70ca656293de289d999b31702ea5e6d25a1281a
I guess that it can be a reference for the Objective-C fix as well.

**Comment by pronebird** [comment]
#308 solves this in Objective-C

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
