### ISSUE TITLE
Auto generate description method

### ISSUE THREAD

**Issue by fraserscottmorrison** [rentzsch/mogenerator#312]
It'd be awesome if mogenerator also generated the description method so, if you inspect/print a NSManagedObject when debugging, all its contents print out to the console

Objective C eg
```objc
- (NSString *)description {
    return [NSString stringWithFormat:@"%@", [self dictionaryRepresentation]];
}

- (NSDictionary *)dictionaryRepresentation {
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    [dict setValue:self.identifier forKey:@"identifier"];
    [dict setValue:self.firstName forKey:@"name"];
    return dict;
}
```
Swift eg:
```swift
    override var description: String {
        return dictionaryRepresentation().description
    }
    func dictionaryRepresentation() -> [NSObject : AnyObject] {
        var mutableDict: [NSObject : AnyObject] = Dictionary()
        if self.identifier != nil {
            mutableDict.updateValue(self.identifier, forKey: "identifier")
        }
        if self.contextText != nil {
            mutableDict.updateValue(self.contextText, forKey: "contextText")
        }
        return mutableDict
    }
```

**Comment by rentzsch** [comment]
I like the `dictionaryRepresentation` generation idea. However `-[NSManagedObject description]` returns useful beyond mo contents, so I don't think overriding it wholesale is the way to go?

**Comment by fraserscottmorrison** [comment]
How about appending them?

**Comment by rentzsch** [comment]
Could work. Can you give me some example output?

**Comment by pronebird** [comment]
Why do you need this? Debugger prints out the entire contents of managed objects.

**Comment by halmueller** [comment]
I don't see this as an improvement. Printing "all of its contents" to console will be clutter, for complicated Entities. How about calling it "func dictionaryDescription: String" instead? It avoids cluttering up description/debugDescription with what will be a lot of noise for most applications.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
