### ISSUE TITLE
Question: 0 human files generated

### ISSUE THREAD

**Issue by gekitz** [rentzsch/mogenerator#316]
I run mogenerator like that
`mogenerator -m meisterwork.xcdatamodeld -O ModelObjects --swift`

and gives me the following output.

`4 machine files and 0 human files generated.`

It never generates any human files, I don't quite understand why. The generated machine files aren't usable since they don't compile because their names are `_.<object-name>`, it seems like the `.` is the problem.

Am I doing something wrong or is this a known issue?

Thanks for helping,
Georg

**Comment by justin** [comment]
Make sure you have an entity name and the module set for each of your xcdatamodel entity objects in Xcode.

**Comment by gekitz** [comment]
It looks like this, should be fine, right?
https://www.dropbox.com/s/xmf8vrw0hjxs6l2/Screenshot%202016-02-10%2017.08.40.png?dl=0

**Comment by gekitz** [comment]
Okay it seems that I get the generated files if I change the module from `Current Product Module` to something else. Is this expected to be like that?

**Comment by justin** [comment]
That should be fine. I've only ever seen the blank file thing when a module isn't set. I haven't experimented with a different module values much though.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!
