### ISSUE TITLE
Update homebrew formula

### ISSUE THREAD

**Issue by 3lvis** [rentzsch/mogenerator#320]
Hi guys,

Are there any plans to update the [homebrew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mogenerator.rb)?

Using `brew update && brew upgrade mogenerator` is updating to 1.29.

**Comment by justin** [comment]
@rentzsch is working on it.

**Comment by 3lvis** [comment]
:clap: Thanks for such quick response @justin! I'll close this one since this tasks is already in progress.
