### ISSUE TITLE
Swift 2.2 Fetched relationships in 1.30

### ISSUE THREAD

**Issue by TomCarey** [rentzsch/mogenerator#322]
Fetched relationships in swift are generated with the source class in the type as opposed to the destination class. ie. 

```
class _A: NSManagedObject {
    ...
    // MARK: - Relationships

    @NSManaged public
    var epicFetchedRelationship: [A]
}
```

when it should have been `var epicFetchedRelationship [B]`

**Comment by justin** [comment]
Any chance you could whip up a quick sample about if you can't provide a patch? It'll help me get it knocked out faster.
