### ISSUE TITLE
Command /bin/sh failed with exit code 134

### ISSUE THREAD

**Issue by colasbd** [rentzsch/mogenerator#324]
I have the same issue as in [issue 169](https://github.com/rentzsch/mogenerator/issues/169).

I have created a new version of my model. Then I run `mogenerator` and it does not work. First time it happens here. With Xcode 7.3.

**Comment by colasjojo** [comment]
The mistake was mine. The new attributes created conflicts. Plus some entities were deleted but not the corresponding relationships. 

Before reading the errors, I just looked at the exit code and found with google (issue 169)[https://github.com/rentzsch/mogenerator/issues/169]. But reading the errors helped me.

I leave the issue open, in case of. Feel free to close if it is useless.

**Comment by colasbd** [comment]
:+1:
