### ISSUE TITLE
Module import breaks projects with Objective-C++ Code

### ISSUE THREAD

**Issue by melbic** [rentzsch/mogenerator#325]
V 1.30 breaks projects which use Objective-C++ code, because modules aren't supported there.
Is there any chance to change the code to something like this? 
```Objective-C
#if __has_feature(modules)
    @import CoreData;
#else
    #import <CoreData/CoreData.h>
#endif
```
(Copied the idea from here (https://github.com/stripe/stripe-ios/issues/220#issuecomment-136374189) 

I could do a pull request if you're willing to merge it.

**Comment by justin** [comment]
Yep. we'd for sure take that. Thanks for doing it!

- j

**Comment by rentzsch** [comment]
@melbic I'm going to do a bug fix release of mogenerator for [this](https://github.com/rentzsch/mogenerator/commit/1646a154c8d9bb2e12b3f23eaca3bbfe9f9bc7c8).

Will you be able to issue the Pull Request in the next day or two or want to catch the next train?

**Comment by melbic** [comment]
I'll try to do it today. If you don't get PR by tonight I'll catch the next one.

**Comment by melbic** [comment]
I tested it with my project which didn't compile with the new version and this does the trick.

**Comment by rentzsch** [comment]
@melbic thanks for 1) filing the issue 2) fixing it 3) turning it around quickly. So like triple-thanks!
