### ISSUE TITLE
Int value properties for NSNumbers, in Swift

### ISSUE THREAD

**Issue by fraserscottmorrison** [rentzsch/mogenerator#326]
### Feature Request

One thing I love about Mogenerator for ObjC is the auto generated primitive properties that unwrap NSNumbers

Are you planning on doing this for Swift? Ive started doing the following in the 'human' classes, but it'd be great to have it automatically built into the machine classes

```swift
    var identifierValue: Int? {
        get {
            if let identifier = self.identifier as NSNumber? {
                return identifier.integerValue
            }
            else {
                return nil
            }
        }
        set {
            if let intVal = newValue as Int? {
                self.identifier = NSNumber(int: Int32(intVal))
            }
            else {
                self.identifier = nil
            }
        }
    }
```

**Comment by justin** [comment]
See ticket #302 for a bit of discussion on this. I have been a bit stuck with other responsibilities to deal with it lately, but we're trying to find a way to make mogen a better Swift player.

**Comment by fraserscottmorrison** [comment]
Thanks
