### ISSUE TITLE
EntityAttributes should also be present in ChildEntity-Attributes

### ISSUE THREAD

**Issue by georgbachmann** [rentzsch/mogenerator#328]
### Feature Request

Here's an example
I have `Entity1` with an attribute named `timestamp`
I also have `Entity2` that inherits from `Entitiy1`, so it also has attribute `timestamp` inherited

Here's where it makes a difference:

If I now want to write  an `NSFetchRequest` for `Entity2` with an `NSPredicate` I would have to write `Entitiy1Attributes.timestamp`. If for whatever reason one day `Entitiy2` will no longer inherit from `Entity1`, that will be a runtime crash...

So it would be nice, if `Entitiy2` would also inherit all the Attributes. I know it's duplication of code, but it would make everything saver?!? But then I could write `Entitiy2Attributes.timestamp` and if `Entitiy2` will one day no longer inherit from `Entity1`, the Attribute will go away and I will get a compile error.

What do you think?

**Comment by iv-mexx** [comment]
I personally ran into this once already so I would welcome that.

**Comment by rentzsch** [comment]
I can see the benefit of this feature. My main concern is the complexity of the implementation. I *think* it would be straight-forward, but Famous Last Words.

**Comment by justin** [comment]
Yeah, I'm worried we don't have the infrastructure to even support this right now given how the generator is built. Not opposed to it, but i think we may need more work internally before its feasible.

**Comment by rentzsch** [comment]
closed by #360
