### ISSUE TITLE
Attribute.isOptional always returns true

### ISSUE THREAD

**Issue by bewebste** [rentzsch/mogenerator#329]
This is basically a re-requesting of #286. The XML for a MOM will only contain an "optional" attribute if the "Optional" checkbox for the property is checked. If the box is not checked, then the XML element has no attribute with this name at all. Since initializing an NSPropertyDescription bare has a default value of YES for its "optional" attribute, this results in that attribute always being YES.

The problem is easily solved by adding a "propertyDescription.optional = NO;" in +[NSPropertyDescription baseEntityForXML:] to make the default value match what happens when there is no attribute in the XML element. I can file a pull request if you need it, but my Github-fu is terrible, so it'll take me some work to figure out how.

**Comment by justin** [comment]
We'll take it. 

The general workflow can be done through the GitHub UI:

1. Fork mogenerator.
2. Create a new branch on your fork to make your changes
3. Add your fix to your branch.
4. Generate a pull request pointing at your branch back to here.

Feel free to bug me if you need any other GitHub help!

**Comment by bewebste** [comment]
Blerg, checked out master and discovered I had just done some funky branching and this was actually fixed some time ago. Nevermiiiiind! *disappears in puff of smoke*
