### ISSUE TITLE
Unicode characters in *.motemplate files

### ISSUE THREAD

**Issue by sryze** [rentzsch/mogenerator#334]
Does mogenerator support Unicode?

When I insert a Unicode character, for example ©, the output file contains some weird extra symbol before the actual copyright sign. If I type something in Russian the text is completely lost:

### Expected Behavior

```
Copyright © 2016
Привет!
```

### Actual Behavior

```
Copyright Â© 2016
ÐÑÐ¸Ð²ÐµÑ!
```

### Additional Information

mogenerator 1.30

I double-checked the Text Encoding setting in file properties in Xcode, it's set to Unicode (UTF-8) for both files.

**Comment by rentzsch** [comment]
mogenerator *should* support UTF-8, but I wouldn't be surprised if there isn't a bug in MiscMerge or how mogenerator is using it that's wrong.

This *looks* right to me:

- <https://github.com/rentzsch/mogenerator/blob/master/MiscMerge/MiscMergeTemplate.m#L135>
- <https://github.com/rentzsch/mogenerator/blob/master/mogenerator.m#L654>

I encourage you to download mogenerator's code, debug it in Xcode if this is an important issue for you. Hint: use Edit Scheme > Run > Arguments to populate mogenerator's arguments so it's easy to run and re-run for debugging.

**Comment by sryze** [comment]
It seems to work with latest mogenerator from git. I was using version 1.30 but the UTF-8 support apparently was fixed between 1.30 and 1.30.1. 

Thanks!
