### ISSUE TITLE
Machine files raise lots of errors with -Wnullable-to-nonnull-conversion

### ISSUE THREAD

**Issue by ibsh** [rentzsch/mogenerator#336]
With the introduction of proper nullability in Objective-C machine consumption headers (thank you!), there are multiple errors raised with the -Wnullable-to-nonnull-conversion flag (which my team has adopted for ease of adding Swift to our legacy Objective-C codebase). For example (and this is almost certainly not exhaustive):
1. All implementations of +entityInManagedObjectContext: are invalid, as the internal NSEntityDescription#entityForName:inManagedObjectContext: call has a nullable return
2. Implementations of CoreDataGeneratedAccessors are invalid for nullable collection properties

I guess for 1), it would be best to mark +entityInManagedObjectContext: as nullable.
Conditional code will be necessary for 2).

**Comment by rentzsch** [comment]
Thanks!
