### ISSUE TITLE
Document steps after installation

### ISSUE THREAD

**Issue by mikekloster** [rentzsch/mogenerator#34]
I had to google what to do after installation to cause the auto code generation to take effect.

I found this link: http://stackoverflow.com/questions/3563145

An answer is provided by Marcus S. Zarra. I'll summarize below.

The explanation is very simple. After installing, right click your .xcdatamodel file, select "Get Info" then select the "Comments" tab. In the comments section at the text: "xmod". 

The "xmod" in the comments tab is the flag that causes mogenerator to generate files. This gives you the ability to enable / disable generation per .xcdatamodel.

**Comment by justin** [comment]
Xmox is RIP. Closing this out.
