### ISSUE TITLE
Error while building application in xcode

### ISSUE THREAD

**Issue by praveen4565** [rentzsch/mogenerator#348]
Am very new to mogenerator. Am trying to build my application, mean while am getting below error.
I tried searching in google.But, no information. Can anyone please help me to resolve this?

Xcode - 7.3.1 (swift project)

app/Scripts/runmogenerator.sh: line 2: 
: command not found
Generate Convenience-Classes for Core Data With MOGenerator
app/Scripts/runmogenerator.sh: line 4: 
: command not found
app/Scripts/runmogenerator.sh: line 5: set: -
: invalid option
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
Command /bin/sh failed with exit code 2

**Comment by praveen4565** [comment]
Can anyone help me to resolve the issue

**Comment by rentzsch** [comment]
<http://www.catb.org/~esr/faqs/smart-questions.html>
