### ISSUE TITLE
Abort Trap 6 

### ISSUE THREAD

**Issue by rrgood** [rentzsch/mogenerator#351]
When attempting to run mogenerator from the terminal I get:

[Radar.xcdatamodeld.zip](https://github.com/rentzsch/mogenerator/files/509685/Radar.xcdatamodeld.zip)
Richards-iMac:Qinlin rrg$ mogenerator -m Radar.xcdatamodeld/Radar.xcdatamodel -O Coredata --swift --template-var arc=true
Assertion failed: (property), function -[NSEntityDescription(customBaseClass) _resolveKeyPathType:], file /Users/wolf/code/github/mogenerator/mogenerator.m, line 313.
Abort trap: 6

**Comment by rentzsch** [comment]
You have a bug in your model. `fetchByID` references `DBObject` `internalID`, which it doesn't have.

Yes, mogenerator's error could be much better here. Pull Requests welcome.

**Comment by rrgood** [comment]
Thank you.  Really appreciate the quick response, and your open source generosity.

Richard Good
C.T.O. trueIDapps
(619) 248 7381

http://www.goodschooltools.com <http://www.trueidapps.com/>



 <http://itunes.apple.com/us/app/trueidsuite/id414351392?ls=1&mt=8>  <http://itunes.apple.com/us/app/trueidsuite/id414351392?ls=1&mt=8>           <https://itunes.apple.com/us/app/student-lists-for-school-staff/id956566787?mt=8>   <https://itunes.apple.com/us/app/student-lists-for-school-staff/id956566787?mt=8>        <https://itunes.apple.com/us/app/tardy/id817033756?mt=8>

trueidSuite <https://itunes.apple.com/us/app/trueidsuite/id414351392?mt=8>          <https://itunes.apple.com/us/app/student-lists-for-school-staff/id956566787?mt=8>Student Lists <https://itunes.apple.com/us/app/student-lists-for-school-staff/id956566787?mt=8>          Tardy <https://itunes.apple.com/us/app/tardy/id817033756?mt=8>
