### ISSUE TITLE
Swift generated code creates NSNumber for boolean types

### ISSUE THREAD

**Issue by randyhill** [rentzsch/mogenerator#364]
### Feature Request

I would like boolean attributes in my entities to be generated as Bool types in Swift.

### Question

Nothing is, Im trying to use Mogenerator/Core Data for first time so my apologies if I'm misunderstanding how everything works. I tried marking the attributes as Scalar Types and not Scalar Types, but nothing changed.

### Expected Behavior

I would think they would be generated as Bools.

### Actual Behavior

They are generated as NSNumber.

### Additional Information

Xcode 8.2, Mogenerator 1.31

**Comment by pronebird** [comment]
Use `*Value` accessors?
