### ISSUE TITLE
Issue with setPrimitive...: for Transformable attributes

### ISSUE THREAD

**Issue by colasbd** [rentzsch/mogenerator#366]
## Situation
I have an `NSArray` (of `NSString`s) transformable attribute called `namesTopics` in my model.
I have override the `setNamesTopics:` method as follows
```
- (void)setNamesTopics:(NSArray *)namesTopics
{
    [self setPrimitiveNamesTopics:namesTopics];
    _stringOfTopics = nil;
}
```

## Issue
Once `namesTopics` is set for the first time, I cannot change it.
If I change it, there is no issue and the change is saved in the in-memory data.
But if I quit the application and open my data again, I can see that the changes have not been persisted.

## Temporary solution
So far, I have done this: I don't use the `setNamesTopics:` method anymore, I use instead `- (void)setEffectiveNamesTopics:(NSArray *)namesTopics` defined by
```
- (void)setEffectiveNamesTopics:(NSArray *)namesTopics
{
    self.namesTopics = namesTopics;
    _stringOfTopics = nil;
}
```
and it works.

## Conclusion
There seems to be an issue with `setPrimitive...:` and Transformable attributes.

**Comment by atomicbird** [comment]
This looks like it's about Core Data primitive accessors, and not specific to `mogenerator`. If you use one of the "primitive" accessor methods, you need to include additional code to trigger KVO actions in Core Data-- in this case the "will change" and "did change" methods. Your code would be something like

```objc
    [self willChangeValueForKey:@"namesTopics"];
    [self setPrimitiveNamesTopics:namesTopics];
    [self didChangeValueForKey:@"namesTopics"];
```

You'd probably have the same problem any time you override an accessor, not just with transformables and not just with `mogenerator`.
