### ISSUE TITLE
There is mo mogenerator's folder in /Library/Application Support after successful installation.

### ISSUE THREAD

**Issue by MikeGlotov** [rentzsch/mogenerator#381]
### Feature Request

_What would you like to see that is not currently available?_

### Question

_What is not clear?_

### Expected Behavior

There should be a folder where I could place my templates.

### Actual Behavior

There is no such folder and because of that, I'd like to know how can I add my templates?

### Additional Information

Enterprise MacBook Pro, OS - Mojave 

Thank you for any help.

**Comment by atomicbird** [comment]
If you have custom template files, you can put them anywhere you like. Use the `--template-path` command line argument to tell `mogenerator` where to find them.

**Comment by atomicbird** [comment]
Closing this because it looks like you should be OK, let me know if not.
