### ISSUE TITLE
Trying to find swift template files outside of template-group

### ISSUE THREAD

**Issue by ebaker355** [rentzsch/mogenerator#382]
### Question

My project directory structure looks like this:
```
Project/
    Resources/
        DataModel.xcdatamodeld/
            DataModel.xcdatamodel
    mogenerator_templates/
        MyBaseClass.[h, m]
        human.[h, m, swift].motemplate
        machine.[h, m, swift].motemplate
```

At the Project root, I run this command to generate my file:

`mogenerator --swift --base-class CoreModel --model Resources/DataModel.xcdatamodeld --output-dir /Volumes/RamDisk --template-path ../ --template-group mogenerator_templates`

(I have a mounted RamDisk for the output)

Am I using the --template-path and --template-group arguments correctly? Documentation is a little vague.
 
### Expected Behavior

The template files should be read from the mogenerator_templates directory and used to generate the files.

### Actual Behavior

It seems mogenerator is not always using the proper path to find the template files. This is the output:

```
2019-01-26 11:28:45.369 mogenerator[25215:307775] MiscMergeTemplate: Could not read template file Resources/../machine.swift.motemplate because The file “machine.swift.motemplate” couldn’t be opened because there is no such file.
2019-01-26 11:28:45.369 mogenerator[25215:307775] NSScanner: nil string argument
2019-01-26 11:28:45.369 mogenerator[25215:307775] MiscMergeTemplate: Could not read template file Resources/../human.swift.motemplate because The file “human.swift.motemplate” couldn’t be opened because there is no such file.
2019-01-26 11:28:45.369 mogenerator[25215:307775] NSScanner: nil string argument
7 machine files and 7 human files generated.
```

Additionally, the files _are_ created in the output directory, but they are all empty. They contain no output.

### Additional Information

I can workaround this issue by doing:

```
ln -s mogenerator_templates/human.swift.motemplate human.swift.motemplate
ln -s mogenerator_templates/machine.swift.motemplate machine.swift.motemplate
```

With these links in place, the file are generated as expected.

(However, using unmodified template files from the GitHub repo, mogenerator reports `Caught: NSUnknownKeyException: [<NSAttributeDescription 0x7fb89bc209c0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key usesScalarAttributeType.`. This error does not occur if I do not use templates. I can workaround this by removing references to `usesScalarAttributeType` in my custom templates. But this is a separate issue.)

Thanks! mogenerator is fantastic! 🍺

**Comment by atomicbird** [comment]
From your description, you should use only `--template-path`. Using `--template-group` is having no effect because `--template-path` takes precedence. When it's present, `--template-group` is ignored (yes this should be explained somewhere).

The value of `--template-path` is a path to the directory where templates are located, either absolute or relative to the current directory. From your description I think what you need is `--template-path mogenerator_templates`, assuming that the current directory is the one which contains the template directory.

I'll look into the problem with the unmodified templates.

**Comment by atomicbird** [comment]
@ebaker355 I'm not able to reproduce a problem with `usesScalarAttributeType` with the latest commits from the repo. If you still see this, please add some more detail so I can track down the problem.

**Comment by ebaker355** [comment]
@atomicbird Thanks for the clarification about `--template-group`. I will play around with it some more as I have time.

As for the `usesScalarAttributeType` issue, here are a few more details:

- I have mogenerator installed via homebrew.

```
> mogenerator --version
mogenerator 1.31. By Jonathan 'Wolf' Rentzsch + friends.
```

- I have downloaded the template files from the mogenerator repo into the mogenerator-templates directory. The files have not been modified.
- When I run mogenerator with the command shown above (without the `--template-group` arg), I receive the `this class is not key value coding-compliant for the key usesScalarAttributeType` exception.
- If I omit the `--template-path` arg and do not provide any templates, then mogenerator succeeds and produces the expected swift files (human and machine).

Transcript:

```
> pwd
/Users/eric/Documents/Code/ios_core/Resources

> ls -lR
total 0
drwxr-xr-x@  3 eric  staff   96 Jan 21 07:27 DataModel.xcdatamodeld
drwxr-xr-x  11 eric  staff  352 Jan 29 16:55 mogenerator_templates

./DataModel.xcdatamodeld:
total 0
drwxr-xr-x  3 eric  staff  96 Jan 21 07:27 DataModel.xcdatamodel

./DataModel.xcdatamodeld/DataModel.xcdatamodel:
total 56
-rw-r--r--  1 eric  staff  24647 Jan 21 07:27 contents

./mogenerator_templates:
total 120
-rwxr-xr-x@ 1 eric  staff    138 Jan 22 19:54 MyBaseClass.h
-rwxr-xr-x@ 1 eric  staff    143 Jan 22 19:54 MyBaseClass.m
-rwxr-xr-x@ 1 eric  staff    141 Jan 22 19:54 human.h.motemplate
-rwxr-xr-x@ 1 eric  staff    200 Jan 22 19:54 human.m.motemplate
-rwxr-xr-x@ 1 eric  staff    152 Jan 22 19:54 human.swift.motemplate
-rwxr-xr-x@ 1 eric  staff   9374 Jan 22 19:54 machine.h.motemplate
-rwxr-xr-x@ 1 eric  staff  15152 Jan 22 19:54 machine.m.motemplate
-rwxr-xr-x@ 1 eric  staff  11138 Jan 22 19:54 machine.swift.motemplate

> mogenerator --swift --base-class CoreModel --model DataModel.xcdatamodeld --output-dir /Volumes/RamDisk --template-path ./mogenerator_templates
Caught: NSUnknownKeyException: [<NSAttributeDescription 0x7f8126d1c390> valueForUndefinedKey:]: this class is not key value coding-compliant for the key usesScalarAttributeType.

> mogenerator --swift --base-class CoreModel --model DataModel.xcdatamodeld --output-dir /Volumes/RamDisk
7 machine files and 5 human files generated.
```

However, if I modify the machine.swift.motemplate file by 1) removing all references to `usesScalarAttributeType` and 2) adding a custom comment at the top of the file, I get:

```
> mogenerator --swift --base-class CoreModel --model DataModel.xcdatamodeld --output-dir /Volumes/RamDisk --template-path ./mogenerator_templates
7 machine files and 7 human files generated.

> head -10 /Volumes/RamDisk/_User.swift
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// Make changes to User.swift instead.
// custom template output

import Foundation
import CoreData

public enum UserAttributes: String {
    case createdAt = "createdAt"
    case email = "email"
```

The generated file includes my "custom template output" header comment, so I know the template files are being used. My model definitely needs to use scalars, so I would like to include `usesScalarAttributeType` in my custom templates.

Please let me know if I can provide any more information. I am going to keep poking at it, perhaps with a simpler data model for testing.

Thanks!

**Comment by atomicbird** [comment]
Thanks for the info. I'm not completely certain what's up but it seems to be related to how Homebrew gets mogenerator files. If I install via Homebrew I get the same error, but if I build from source it works. I'll look into it and figure out what needs to change.

For what it's worth, if you're not modifying the template files, you don't need to download them. The templates are compiled into the binary. You wouldn't normally need to use `--template-path` unless you have customized them.

**Comment by atomicbird** [comment]
OK, the problem is simply that Homebrew is pulling down the latest release (1.31) but there are a bunch of changes in `master` since then, which includes template file changes that don't work with 1.31. I'll see about getting a new release ready that includes more recent changes, and getting Homebrew to use that once it's available.

**Comment by ebaker355** [comment]
Thank you! I'll also pull down and build the master branch. For now, I can just use my own binary.

**Comment by ebaker355** [comment]
I can confirm that running a build of the master branch does indeed fit the `usesScalarAttributeType` issue.

**Comment by atomicbird** [comment]
Good to hear. Version 1.32 is now released, which should resolve any related issues going forward.
