### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by mecoFarid** [rentzsch/mogenerator#392]
I can see there has been no contribution since 2 years and wonder if silence is for "**everything is perfect and there has been no need for further development**" or "**is it end of it**"?

**Comment by rentzsch** [comment]
mogenerator has always been demand-paged, and there hasn't been much demand for a while.

A big reason is Apple's [finally](https://twitter.com/rentzsch/status/743866055081111552) adding code generation directly into Xcode. That covers most developers' requirements.

So I'd say it's "everything is (mostly good) and there has been no need for further development", at least for my purposes.
