### ISSUE TITLE
Support @properties that are 'copy' in addition to the default 'retain'

### ISSUE THREAD

**Issue by seanm** [rentzsch/mogenerator#41]
mogenerator always creates properties that are 'retain', which is a sensible default, but I'd like to see it able to generate 'copy' properties too.

Perhaps this could be done using the user info dictionary, like how transformable attributes can specify an 'attributeValueClassName' key/value pair.

**Comment by justin** [comment]
This is ancient. Closing it out. If its still an issue for you, please open a new issue.
