### ISSUE TITLE
Automatic generation for versioned data models

### ISSUE THREAD

**Issue by nvie** [rentzsch/mogenerator#7]
When you have added a version to your Core Data model (Design > Data Model > Add Model Version), automatic entity generation using the 'xmod' comment text stops working.

It's not exactly clear to me whether this should work, is still unimplemented, or whether the 'xmod' comment tag should be placed elsewhere (for example on the .xcdatamodeld directory?).

Any experiences with versioned models and auto-generating classes?

**Comment by pronebird** [comment]
I've been brought here by the following warning and I have no idea what the hell is going on. Can anyone elaborate?

```
WARNING skipping 'type' attribute on Blah (BlahModel) - see https://github.com/rentzsch/mogenerator/issues/74
```
