### ISSUE TITLE
iOS 5.1 SDK Seems to Break Scalars

### ISSUE THREAD

**Issue by jeffmcfadden** [rentzsch/mogenerator#96]
"No visible interface for 'NSNumber' declares the selector int32_tValue"

Here's the generated code that's throwing that error:

``` objective-c


- (int32_t)idValue {
    NSNumber *result = [self id];
    return [result int32_tValue];
}

- (void)setIdValue:(int32_t)value_ {
    [self setId:[NSNumber numberWithInt32_t:value_]];
}

```

**Comment by mac10688** [comment]
How does one update the templates? I just installed mogenerator today and I'm trying to compile a project for the first time. I'm getting errors in what appears to be the Generated models. Does that mean I have up to date templates? I did install with homebrew if that matters.
